### ISSUE TITLE
API is not returning the call to your localhost.

### ISSUE THREAD

**Issue by ghost** [pbaisla/artist-finder#1]
![apicall](https://cloud.githubusercontent.com/assets/2974077/5536974/0e9f290c-8ac0-11e4-9db2-7dd6f673aff2.png)
I got some free time yesterday to check upon some stuff. So i thought of executing your application. When you run the application outside of proxy env the application works find and artist information is displayed too but when you try to execute your application inside proxy it works return anything. 
I think so someway out api call isn't getting our server address.
These is one of the major bug been facing with some of api's. Check it out......

**Comment by pbaisla** [comment]
Thanks for reporting this!
I finally got a chance to test this out in a proxy environment and was able to reproduce the problem.

The problem is that our API call isn't even reaching lastfm. The request made by the rails server doesn't have the proper proxy authentication set so the proxy server isn't forwarding the request.

One possible way to solve this problem is to use something like [proxychains](http://proxychains.sourceforge.net/). After you've downloaded that and configured it with your proxy settings, you can run the app like this 
`proxychains rails server`
and it should work just fine.

**Comment by ghost** [comment]
Good Call. But in my case api wasn't reaching the host, I wrote some script for that. There are many application which can chain proxy but i believe these can be configure in config file. Hey have reached college?
